Repository terra-money/terra.js, pull requests merged in 2021-08, with the labels that each got.

#113 [Feature Proposal ]Add Axios query params in each API get method.
  src/client/lcd/APIRequester.ts
  src/client/lcd/api/AuthAPI.ts
  src/client/lcd/api/BankAPI.ts
  src/client/lcd/api/DistributionAPI.ts
  src/client/lcd/api/GovAPI.ts
  src/client/lcd/api/MarketAPI.ts
  src/client/lcd/api/MintAPI.ts
  src/client/lcd/api/MsgAuthAPI.ts
  src/client/lcd/api/OracleAPI.ts
  src/client/lcd/api/SlashingAPI.ts
  src/client/lcd/api/StakingAPI.spec.ts
  src/client/lcd/api/StakingAPI.ts
  src/client/lcd/api/SupplyAPI.ts
  src/client/lcd/api/TendermintAPI.ts
  src/client/lcd/api/TreasuryAPI.ts
  src/client/lcd/api/TxAPI.ts
  src/client/lcd/api/WasmAPI.ts
Labels: enhancement

#112 Fix GovAPI endpoints (deposits, votes) and handle LCD API return null in a Coins.Data value.
  src/client/lcd/api/GovAPI.ts
  src/core/Coins.ts
  src/core/Deposit.ts
  src/core/Vote.ts
  src/core/index.ts
Labels: bug, enhancement

#120 [Feature] Remove null property from wasm execute msg
  package-lock.json
  package.json
  src/core/wasm/msgs/MsgExecuteContract.ts
  src/core/wasm/msgs/MsgInstantiateContract.ts
  src/core/wasm/msgs/MsgMigrateContract.ts
  src/util/json.spec.ts
  src/util/json.ts
Labels: enhancement, columbus-5
