Repository terra-money/terra.js, pull requests merged in 2021-09, with the labels that each got.

#126 Support query parameters for {lcd}/gov/proposals
  package-lock.json
  package.json
  src/client/lcd/api/GovAPI.ts
Labels: enhancement

#125 Governance breaking changes for Columbus-5
  package-lock.json
  package.json
  src/core/Vote.ts
  src/core/gov/Proposal.ts
  src/core/gov/Vote.ts
  src/core/gov/msgs/MsgSubmitProposal.ts
  src/core/gov/msgs/MsgVote.ts
  src/core/gov/msgs/MsgVoteWeighted.ts
  src/core/gov/msgs/index.ts
  src/core/index.ts
Labels: enhancement, columbus-5

#142 Backport upgrade module to 2.0.x
  package-lock.json
  package.json
  src/core/gov/Proposal.ts
  src/core/gov/Vote.ts
  src/core/upgrade/Plan.spec.ts
  src/core/upgrade/Plan.ts
  src/core/upgrade/proposals/CancelSoftwareUpgradeProposal.spec.ts
  src/core/upgrade/proposals/CancelSoftwareUpgradeProposal.ts
  src/core/upgrade/proposals/SoftwareUpgradeProposal.spec.ts
  src/core/upgrade/proposals/SoftwareUpgradeProposal.ts
  src/core/upgrade/proposals/index.ts
Labels: enhancement, columbus-5

#143 Remove Denom.LUNA, Denom.USD, ... for sustainablity
  README.md
  integration-tests/estimateFee.ts
  integration-tests/executeContract.ts
  integration-tests/submitProposal.ts
  integration-tests/validatorsWithVotingPower.ts
  package-lock.json
  package.json
  src/client/lcd/LCDUtils.spec.ts
  src/client/lcd/api/StakingAPI.ts
  src/client/lcd/api/TreasuryAPI.ts
  src/core/Coin.spec.ts
  src/core/Coins.spec.ts
  src/core/Denom.ts
  src/core/TxInfo.data.json
Labels: enhancement

#144 fix type for deposits and votes
  package-lock.json
  package.json
  src/client/lcd/api/GovAPI.ts
Labels: bug
