Repository terra-money/terra.js, pull requests merged in 2021-07, with the labels that each got.

#99 Fix MsgEditValidator bug
  src/core/staking/msgs/MsgEditValidator.data.json
  src/core/staking/msgs/MsgEditValidator.ts
Labels: bug

#102 Fix minor regular expression bug
  package-lock.json
  package.json
  src/client/lcd/api/TxAPI.ts
Labels: bug, columbus-5

#103 Increase default gas adjustment
  integration-tests/estimateFee.ts
  package-lock.json
  package.json
  src/client/lcd/LCDClient.ts
Labels: enhancement

#107 Handle mismatching coins in estimateFee gasPrices and feeDenoms
  src/client/lcd/api/TxAPI.ts
Labels: enhancement, good first issue

#108 Wasm message compatibility for Bombay/Columbus-5
  package-lock.json
  package.json
  src/client/lcd/APIRequester.ts
  src/client/lcd/LCDClient.ts
  src/client/lcd/api/WasmAPI.ts
  src/util/contract.ts
Labels: bug, enhancement
