Repository terra-money/terra.js, pull requests merged in 2021-06, with the labels that each got.

#79 Update testnet in readme file
  README.md
Labels: documentation, good first issue

#84 Fix GitHub Action Workflows
  .github/workflows/main.yml
  .github/workflows/typedoc.yml
  package-lock.json
  package.json
Labels: bug

#87 Fix breaking changes in staking module
  integration-tests/estimateFee.ts
  integration-tests/validatorsWithVotingPower.ts
  src/client/lcd/LCDUtils.spec.ts
  src/client/lcd/LCDUtils.ts
  src/client/lcd/api/AuthAPI.spec.ts
  src/client/lcd/api/StakingAPI.spec.ts
  src/core/ValidatorSet.ts
  src/core/numeric.ts
  src/core/staking/Delegation.data.json
  src/core/staking/Delegation.ts
  src/core/staking/Redelegation.data.json
  src/core/staking/Redelegation.ts
  src/core/staking/Validator.spec.ts
  src/core/staking/Validator.ts
  src/core/staking/msgs/MsgCreateValidator.data.json
  src/core/staking/msgs/MsgCreateValidator.ts
  src/core/staking/msgs/MsgDelegate.data.json
  src/core/staking/msgs/MsgEditValidator.data.json
  src/core/staking/msgs/MsgEditValidator.ts
  src/core/strings.ts
Labels: columbus-5

#89 Make bundle work in browser
  package-lock.json
  package.json
  src/core/oracle/msgs/MsgAggregateExchangeRateVote.ts
  src/core/oracle/msgs/MsgExchangeRateVote.ts
  src/key/Key.ts
  src/key/RawKey.ts
  src/util/hash.ts
  webpack.config.js
Labels: bug, enhancement

#91 Update jscrypto to 1.0.1
  package-lock.json
  package.json
Labels: enhancement

#92 Dependency upgrades and retire Node.js <= 11
  package-lock.json
  package.json
  src/core/auth/index.ts
Labels: dependencies, enhancement
